from django.utils.translation import gettext_lazy as _


LANGUAGES = [
    ("", _("Select language")),
    (1, _("Afrikaans")),
    (2, _("Arabic")),
    (3, _("Algerian Arabic")),
    (4, _("Asturian")),
    (5, _("Azerbaijani")),
    (6, _("Bulgarian")),
    (7, _("Belarusian")),
    (8, _("Bengali")),
    (9, _("Breton")),
    (10, _("Bosnian")),
    (11, _("Catalan")),
    (12, _("Central Kurdish (Sorani)")),
    (13, _("Czech")),
    (14, _("Welsh")),
    (15, _("Danish")),
    (16, _("German")),
    (17, _("Lower Sorbian")),
    (18, _("Greek")),
    (19, _("English")),
    (20, _("Australian English")),
    (21, _("British English")),
    (22, _("Esperanto")),
    (23, _("Spanish")),
    (24, _("Argentinian Spanish")),
    (25, _("Colombian Spanish")),
    (26, _("Mexican Spanish")),
    (27, _("Nicaraguan Spanish")),
    (28, _("Venezuelan Spanish")),
    (29, _("Estonian")),
    (30, _("Basque")),
    (31, _("Persian")),
    (32, _("Finnish")),
    (33, _("French")),
    (34, _("Frisian")),
    (35, _("Irish")),
    (36, _("Scottish Gaelic")),
    (37, _("Galician")),
    (38, _("Hebrew")),
    (39, _("Hindi")),
    (40, _("Croatian")),
    (41, _("Upper Sorbian")),
    (42, _("Hungarian")),
    (43, _("Armenian")),
    (44, _("Interlingua")),
    (45, _("Indonesian")),
    (46, _("Igbo")),
    (47, _("Ido")),
    (48, _("Icelandic")),
    (49, _("Italian")),
    (50, _("Japanese")),
    (51, _("Georgian")),
    (52, _("Kabyle")),
    (53, _("Kazakh")),
    (54, _("Khmer")),
    (55, _("Kannada")),
    (56, _("Korean")),
    (57, _("Kyrgyz")),
    (58, _("Luxembourgish")),
    (59, _("Lithuanian")),
    (60, _("Latvian")),
    (61, _("Macedonian")),
    (62, _("Malayalam")),
    (63, _("Mongolian")),
    (64, _("Marathi")),
    (65, _("Malay")),
    (66, _("Burmese")),
    (67, _("Norwegian Bokmål")),
    (68, _("Nepali")),
    (69, _("Dutch")),
    (70, _("Norwegian Nynorsk")),
    (71, _("Ossetic")),
    (72, _("Punjabi")),
    (73, _("Polish")),
    (74, _("Portuguese")),
    (75, _("Brazilian Portuguese")),
    (76, _("Romanian")),
    (77, _("Russian")),
    (78, _("Slovak")),
    (79, _("Slovenian")),
    (80, _("Albanian")),
    (81, _("Serbian")),
    (82, _("Serbian Latin")),
    (83, _("Swedish")),
    (84, _("Swahili")),
    (85, _("Tamil")),
    (86, _("Telugu")),
    (87, _("Tajik")),
    (88, _("Thai")),
    (89, _("Turkmen")),
    (90, _("Turkish")),
    (91, _("Tatar")),
    (92, _("Udmurt")),
    (93, _("Ukrainian")),
    (94, _("Urdu")),
    (95, _("Uzbek")),
    (96, _("Vietnamese")),
    (97, _("Simplified Chinese")),
    (98, _("Traditional Chinese")),
]
